version: '3.8'

services:
  frontend:
    build:
      context: ./nextjs-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-here
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - API_BASE_URL=http://backend:5000
    depends_on:
      - backend
    volumes:
      - ./nextjs-frontend:/app
      - /app/node_modules
    networks:
      - coursemate-network

  backend:
    build:
      context: ./flask-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your-secret-key-here
      - JWT_SECRET_KEY=your-jwt-secret-key-here
      - DATABASE_URL=postgresql://coursemate:password@db:5432/coursemate
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db
    volumes:
      - ./flask-backend:/app
    networks:
      - coursemate-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=coursemate
      - POSTGRES_USER=coursemate
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coursemate-network

volumes:
  postgres_data:

networks:
  coursemate-network:
    driver: bridge
